[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

fs_permissions = [
	{ access = "read", path = "./deployments"},
	{ access = "read", path = "./out"}
]

[fuzz]
runs = 1

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
